INPUT:
  MIN_SIZE_TRAIN: (832, 928, 1024)
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TEST: 2560
  MAX_SIZE_TEST: 3840
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  TO_BGR255: False
  # This augmentation is intended for
  # dataset with small motion
  MOTION_LIMIT: 0.1
  MOTION_BLUR_PROB: 1.0
  COMPRESSION_LIMIT: 50
  BRIGHTNESS: 0.1
  CONTRAST: 0.1
  SATURATION: 0.1
  HUE: 0.1

MODEL:
  # The maximum number of frames that a track keeps dormant before it is killed
  TRACK_HEAD:
    MAX_DORMANT_FRAMES: 30
    TRACKLOSS: 'diou'
    SEARCH_REGION: 2.0
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
  RPN:
    ANCHOR_SIZES: (8, 16, 32, 64, 128)
  WEIGHT: 'pretrained/frcnn_dla34.pth'
  

SOLVER:
  # Assume 8 GPUs is 0.02
  BASE_LR: 0.0025
  # BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 100000)
  MAX_ITER: 120000
  VIDEO_CLIPS_PER_BATCH: 1

DATASETS:
  # SET THIS PATH CORRECTLY
  ROOT_DIR: "datasets"
  TRAIN: ("DOTA_AUG_PLANE",)

DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 8


